### ISSUE TITLE
Replace MotorControllerGroup use with follow() methods of drivetrain motors

### ISSUE THREAD

**Issue by Capyblapy** [frc9577/robot_code_2024#5]
The MotorControllerGroup class is deprecated. Replace its use in our code with calls to the primary motor controller's follow() method for each side of the drivetrain.

**Comment by dawilson9** [comment]
This is fixed in the BasicDrive project at commit 8a07e74b in the development branch.

**Comment by Capyblapy** [comment]
The fix has been added to main in PR https://github.com/frc9577/robot_code_2024/pull/4

Can we close this issue?

**Comment by Capyblapy** [comment]
Fixed as of PR #4
